steps:
- script: |
    echo "Removing homebrew from Azure to avoid conflicts."
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
    chmod +x ~/uninstall_homebrew
    ~/uninstall_homebrew -fq
    rm ~/uninstall_homebrew
  displayName: Remove homebrew
- bash: |
    source ${CONDA}/etc/profile.d/conda.sh
    sudo chown -R ${USER} ${CONDA}
    conda config --set always_yes yes --set changeps1 no
    conda update -q conda
    conda info -a
    conda create --name rdkit_build -c conda-forge $(compiler) cmake \
        boost-cpp=$(boost_version) boost=$(boost_version) \
        py-boost=$(boost_version) libboost=$(boost_version) \
        numpy matplotlib cairo pillow eigen pandas
  displayName: Setup build environment
- bash: |
    export MACOSX_DEPLOYMENT_TARGET=$(macosx_deployment_target)
    source ${CONDA}/etc/profile.d/conda.sh
    conda activate rdkit_build
    export RDBASE=`pwd`
    export PYTHONPATH=${RDBASE}:${PYTHONPATH}
    export DYLD_FALLBACK_LIBRARY_PATH=${RDBASE}/lib:${CONDA_PREFIX}/lib:${DYLD_FALLBACK_LIBRARY_PATH}
    export QT_QPA_PLATFORM='offscreen'
    hash -r
    mkdir build && cd build && \
    cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DRDK_INSTALL_INTREE=ON \
    -DRDK_INSTALL_STATIC_LIBS=OFF \
    -DRDK_BUILD_CPP_TESTS=ON \
    -DRDK_BUILD_PYTHON_WRAPPERS=ON \
    -DRDK_USE_BOOST_REGEX=ON \
    -DRDK_BUILD_COORDGEN_SUPPORT=OFF \
    -DRDK_OPTIMIZE_NATIVE=OFF \
    -DRDK_BUILD_TEST_GZIP=OFF \
    -DRDK_BUILD_FREESASA_SUPPORT=OFF \
    -DRDK_BUILD_AVALON_SUPPORT=OFF \
    -DRDK_BUILD_INCHI_SUPPORT=OFF \
    -DRDK_BUILD_SWIG_WRAPPERS=OFF \
    -DRDK_SWIG_STATIC=OFF \
    -DRDK_BUILD_THREADSAFE_SSS=OFF \
    -DRDK_TEST_MULTITHREADED=OFF \
    -DBoost_NO_SYSTEM_PATHS=ON \
    -DPYTHON_EXECUTABLE=${CONDA_PREFIX}/bin/python3 \
    -DCMAKE_INCLUDE_PATH="${CONDA_PREFIX}/include" \
    -DCMAKE_LIBRARY_PATH="${CONDA_PREFIX}/lib"
  displayName: Configure build (Run CMake)
- script: |
    export MACOSX_DEPLOYMENT_TARGET=$(macosx_deployment_target)
    conda activate rdkit_build
    export RDBASE=`pwd`
    export PYTHONPATH=${RDBASE}:${PYTHONPATH}
    export DYLD_FALLBACK_LIBRARY_PATH=${RDBASE}/lib:${CONDA_PREFIX}/lib:${DYLD_FALLBACK_LIBRARY_PATH}
    export QT_QPA_PLATFORM='offscreen'
    cd build
    export
    cat CMakeCache.txt
  displayName: Print out CMakeCache
- bash: |
    export MACOSX_DEPLOYMENT_TARGET=$(macosx_deployment_target)
    source ${CONDA}/etc/profile.d/conda.sh
    conda activate rdkit_build
    export RDBASE=`pwd`
    export PYTHONPATH=${RDBASE}:${PYTHONPATH}
    export DYLD_FALLBACK_LIBRARY_PATH=${RDBASE}/lib:${CONDA_PREFIX}/lib:${DYLD_FALLBACK_LIBRARY_PATH}
    export QT_QPA_PLATFORM='offscreen'
    cd build
    hash -r
    make -j $( $(number_of_cores) ) install
  displayName: Build
- bash: |
    export MACOSX_DEPLOYMENT_TARGET=$(macosx_deployment_target)
    source ${CONDA}/etc/profile.d/conda.sh
    conda activate rdkit_build
    export RDBASE=`pwd`
    export PYTHONPATH=${RDBASE}:${PYTHONPATH}
    export DYLD_FALLBACK_LIBRARY_PATH=${RDBASE}/lib:${CONDA_PREFIX}/lib:${DYLD_FALLBACK_LIBRARY_PATH}
    export QT_QPA_PLATFORM='offscreen'
    cd build
    hash -r
    ctest -j $( $(number_of_cores) ) --output-on-failure
  displayName: Run tests

